title: 我的导航
description: 个人网络导航站
author: 5222
favicon: favicon.ico
logo_text: 导航站

fonts:
  title:
    family: Poppins
    weight: 600
    source: google
  subtitle:
    family: Quicksand
    weight: 500
    source: google
  body:
    family: Noto Sans SC
    weight: 400
    source: google
    
profile:
  title: Hello,
  subtitle: Welcome to My Navigation
  description: 导航菜单222

social:
  - name: GitHub
    url: https://github.com
    icon: fab fa-github
  - name: Telegram
    url: https://t.me
    icon: fab fa-telegram
  - name: Twitter
    url: https://twitter.com
    icon: fab fa-twitter
  - name: Steam
    url: https://steam.com
    icon: fab fa-steam 

ccategories:
  - name: 常用网站
    icon: fas fa-star
    sites:
      - name: Linux.do
        url: https://linux.do/
        icon: fab fa-linux
        description: 新的理想型社区
      - name: Google
        url: https://www.google.com
        icon: fab fa-google
        description: 全球最大的搜索引擎
      - name: GitHub
        url: https://www.github.com
        icon: fab fa-github
        description: 代码托管平台
      - name: Stack Overflow
        url: https://stackoverflow.com
        icon: fab fa-stack-overflow
        description: 程序员问答社区
      - name: ChatGPT
        url: https://chat.openai.com
        icon: fas fa-robot
        description: AI智能助手
